# Generated by Django 2.1 on 2018-09-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
