# Generated by Django 2.1 on 2018-09-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
